/* 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
 */
import { DM_Serif_Display, Space_Mono, DM_Sans } from 'next/font/google'
import "./globals.css";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

const dmSerif = DM_Serif_Display({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal', 'italic'],
  variable: '--font-serif',
})

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-mono',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Sara Abouroumia — Full Stack Engineer',
  description: 'Full stack software engineer specialising in cloud, deployment, and production systems.',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${dmSerif.variable} ${spaceMono.variable} ${dmSans.variable}`}
      >{children}</body>
    </html>
  );
}
